config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  scope '(/:locale)', locale: /ja|en/ do
    devise_for :users
    resources :privacy_policy_acceptances, only: %i[new create index]
    get 'pending_device', to: 'devices#pending', as: :pending_device

    authenticate :user do
      resources :announcements
      resources :invoices, only: %i[index new create update destroy] do
        member do
          get :pdf, defaults: { format: :pdf }
        end
      end
      resources :category_resources, except: %i[show]
      resources :courses, except: %i[destroy] do
        resources :course_lesson_uploads, only: %i[create new show]
      end
      resources :homeworks, only: %i[index new create destroy edit update]
      resources :csv_exports, only: %i[index new show]
      resources :daily_activities, only: %i[create index update]
      resources :english_classes, only: %i[create index update]
      resources :exercises, only: %i[create index update]
      resources :evening_classes, only: %i[create index update]
      resources :files, only: %i[destroy index show]
      resources :homework_resources, only: %i[destroy index]
      resources :kindy_phonics, only: %i[create index update]
      resources :lessons
      resources :lesson_calendars, only: %i[index]
      resources :lesson_searches, only: %i[index]
      resources :lesson_uses, only: %i[index]
      resources :lesson_versions, only: %i[show update]
      resources :level_changes, only: %i[new create]
      resources :missing_lessons, only: %i[index]
      resources :monthly_materials, only: %i[index]
      resources :notifications, except: %i[edit]
      resources :privacy_policies, only: %i[new create show]
      resources :parents_reports, only: %i[create index update]
      resources :proposals, only: %i[show update]
      resources :phonics_classes, only: %i[create index update]
      resources :phonics_resources, only: %i[destroy]
      resources :plans
      resources :school_classes
      resources :seasonal_activities, only: %i[create index update]
      resources :party_activities, only: %i[create index update]
      resources :event_activities, only: %i[create index update]
      resources :report_card_batches, only: %i[index create] do
        post :regenerate, on: :member
      end
      resources :special_lessons, only: %i[create index update]
      resources :stand_show_speaks, only: %i[create index update]
      resources :tutorials
      resources :tutorial_categories
      resources :user_searches, only: %i[index]
      resources :students, except: %i[destroy] do
        member do
          get :icon_chooser
          get :homework_resources
          get :print_version
          get :report_card_pdf
          get :pearson_report, defaults: { format: :pdf }
        end
      end

      resources :student_searches, only: %i[index update]
      resources :support_requests do
        resources :support_messages, only: %i[create]
      end
      resources :teacher_lessons, only: %i[index show]
      resources :teacher_events, only: %i[index show]
      resources :teacher_resources, only: %i[index]
      resources :tests, except: %i[show] do
        resources :test_results, only: %i[create index update]
      end

      resources :organisations, except: %i[destroy] do
        resources :form_submissions, shallow: true
        resources :form_templates, shallow: true
        resources :schools

        resources :student_uploads, only: %i[create new show]
        patch 'student_uploads', to: 'student_uploads#update', as: :student_uploads_update
        resources :teacher_uploads, only: %i[create new show]
        patch 'teacher_uploads', to: 'teacher_uploads#update', as: :teacher_uploads_update
        resources :parent_uploads, only: %i[create new show]
        patch 'parent_uploads', to: 'parent_uploads#update', as: :parent_uploads_update
        resources :pearson_uploads, only: %i[create new show]
        resources :users, except: %i[destroy]
        resources :admins
        resources :org_admins
        resources :parents
        resources :sales
        resources :school_managers
        resources :teachers
        resources :writers
      end
      post 'reassign_editor', to: 'admins#reassign_editor', as: :reassign_editor
      get 'admin_password_change', to: 'admins#new_password_change', as: :admin_password_change
      post 'admin_password_change', to: 'admins#change_password', as: :admin_change_password
      get 'teacher_homework', to: 'homeworks#teacher_index', as: :teacher_homework

      # Index for KU staff who can see everything
      get 'users', to: 'users#index', as: :users
    end

    authenticate :user, ->(user) { user.is?('Admin') } do
      mount Flipper::UI.app(Flipper) => '/flipper', as: :flipper
      mount MissionControl::Jobs::Engine, at: '/jobs'
      mount PgHero::Engine, at: '/pghero'
      resources :devices, only: [:index, :update, :destroy]
      resources :triggerable_jobs, only: %i[index create]
    end

    authenticated :user do
      root to: 'users#show', as: :authenticated_root
    end

    root to: 'splashes#welcome'
  end

  # Receives inquiries from contact form & forwards to Nakagawa
  post 'inquiries' => 'inquiries#create'

  # Health check endpoint
  get 'up' => 'rails/health#show', as: :rails_health_check
end

app/controllers/uploads/teacher_uploads_controller.rb
# frozen_string_literal: true

class TeacherUploadsController < ApplicationController
  include SampleCsvable

  after_action :verify_authorized, only: %i[create new show update]

  def show
    authorize nil, policy_class: TeacherUploadPolicy
    send_data sample_csv(Teacher::CSV_HEADERS),
              filename: 'sample_teachers_upload.csv'
  end

  def new
    authorize nil, policy_class: TeacherUploadPolicy
    @organisation = authorize(Organisation.find(params[:organisation_id]), :update?)
    @orgs = policy_scope(Organisation)

  end

  def create
    @teacher = authorize Teacher.new(teacher_upload_params.merge(organisation_id: params[:organisation_id]))
    @index = params[:index].to_i
    @status = 'Uploaded'
    return if @teacher.save

    set_errors
  end

  def update
    @teacher = authorize Teacher.find_by(email: teacher_upload_params[:email])
    @index = params[:index].to_i
    @status = 'Uploaded'
    return if @teacher.update(teacher_upload_params)

    set_errors
  end

  private

  def teacher_upload_params
    params.require(:teacher_upload).permit(Teacher::CSV_HEADERS.map(&:to_sym))
  end

  def set_errors
    @errors = @teacher.errors.full_messages.to_sentence
    @status = 'Error'
  end
end

app/views/teacher_uploads/_error.html.haml
:ruby
  id = form = "teacher-#{@index}"
  if @teacher.new_record?
    url = organisation_teacher_uploads_update_path(params[:organisation_id])
    method = :post
  else
    url = organisation_teacher_uploads_path(params[:organisation_id])
    method = :patch
  end

%tr.error{ data: { controller: 'upload-summary',
                   'upload-summary-status-value': 'Error' },
           id: "teacher-row-#{@index}" }
  %td.bg-danger
    = text_field_tag 'teacher_upload[name]',
                     @teacher.name, form:
  %td.bg-danger
    = email_field_tag 'teacher_upload[email]',
                      @teacher.email, form:
  %td.bg-danger
    = password_field_tag 'teacher_upload[password]',
                         '', form:
  %td.bg-danger
    = password_field_tag 'teacher_upload[password_confirmation]',
                         '', form:
  %td.bg-danger
    = form_with model: @teacher, url:, method:,
                html: { class: 'flex items-center justify-center gap-2 p-2',
                        id: } do |f|
      %p Error
      %span.material-symbols-outlined.animate-pulse error

      = hidden_field_tag(:index, @index, form:)
      = f.submit class: 'btn btn-main'
%tr{ id: "teacher-errors-#{@index}" }
  %td.bg-danger{ colspan: 9 }= @errors

app/views/teacher_uploads/_format_explainer.html.haml
%section.w-full.text-center.flex.flex-col.gap-3
  %h3 CSVs should be formatted as follows:
  %table.w-full
    %thead
      %tr
        - Teacher::CSV_HEADERS.each do |header|
          :ruby
            bookend = if header == Teacher::CSV_HEADERS.first
              ' thead-s'
            elsif header == Teacher::CSV_HEADERS.last
              ' thead-e'
            else
              ''
            end

          %th{ class: "thead bg-secondary-50#{bookend}" }= header
    %tbody
      %tr
        %td 陽葵
        %td example@gmail.com
        %td akgsdgh3242%($
      %tr
        - Teacher::CSV_HEADERS.each do |_|
          %td ...
      %tr
        %td Name in Japanese or English
        %td Teacher's email
        %td Teacher's password

app/views/teacher_uploads/_success.html.haml
-# locals: (teacher:)

- redacted = %w[password password_confirmation]

%tr.uploaded{ data: { controller: 'upload-summary',
                      'upload-summary-status-value': 'Uploaded' } }
  - Teacher::CSV_HEADERS.each do |header|
    - next if redacted.include?(header)

    %td.bg-success= teacher.send(header)
  %td.bg-success ****
  %td.bg-success ****
  %td.bg-success.flex.items-center.justify-center.gap-2.p-2
    %p Uploaded
    %span.material-symbols-outlined download_done

app/views/teacher_uploads/create.turbo_stream.haml
= turbo_stream.replace "teacher-row-#{@index}" do
  - if @errors
    = render 'teacher_uploads/error', teacher: @teacher
  - else
    = render 'teacher_uploads/success', teacher: @teacher

= turbo_stream.remove "teacher-errors-#{@index}" unless @errors

app/views/teacher_uploads/new.html.haml
= content_for :head do
  %link{ rel: 'stylesheet',
         href: 'https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined' }

%main.flex.flex-col.gap-12.overflow-y-auto.p-3
  = render 'shared/subtitle', text: t('.create_teachers', org: @organisation.name)

  - if current_user.is?('Admin')
    = render 'organisations/nav',
             orgs: @orgs, active_org: @organisation,
             path_func: :new_organisation_teacher_upload_path

  = render 'teacher_uploads/format_explainer'
  = link_to organisation_teacher_upload_path(current_user.organisation, 1),
            class: 'btn btn-main w-full flex justify-center gap-2' do
    %p= t('.download_sample')
    = inline_svg_tag 'download_icon.svg',
                     class: 'fill-white'

  %section.flex.flex-col.gap-3.border-2.border-main.rounded.p-3
    %h2= t('.create_teachers', org: @organisation.name)
    = form_with scope: :teacher_upload,
                html: { class: 'form',
                        data: { controller: 'teacher-uploader',
                                action: 'teacher-uploader#displayTeachers',
                                'teacher-uploader-org-value': @organisation.id,
                                'teacher-uploader-action-value': 'create',
                                'teacher-uploader-headers-value': Teacher::CSV_HEADERS.to_json },
                        id: 'teacher_create_form' } do |f|
      = f.file_field :file,
                     required: true,
                     data: { 'teacher-uploader-target': 'fileInput' }
      = f.submit t('.create_teachers', org: @organisation.name),
                 class: 'btn btn-main'

  %section.flex.flex-col.gap-3.border-2.border-main.rounded.p-3
    %h2= t('.update_teachers', org: @organisation.name)
    = form_with scope: :teacher_upload,
                html: { class: 'form',
                        data: { action: 'teacher-uploader#displayTeachers',
                                controller: 'teacher-uploader',
                                'teacher-uploader-org-value': @organisation.id,
                                'teacher-uploader-action-value': 'update' },
                        id: 'teacher_update_form' } do |f|
      = f.file_field :file,
                     required: true,
                     data: { 'teacher-uploader-target': 'fileInput' }
      = f.submit t('.update_teachers', org: @organisation.name),
                 class: 'btn btn-main'

app/views/teacher_uploads/update.turbo_stream.haml
= turbo_stream.replace "teacher-row-#{@index}" do
  - if @errors
    = render 'teacher_uploads/error', teacher: @teacher
  - else
    = render 'teacher_uploads/success', teacher: @teacher