config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  scope '(/:locale)', locale: /ja|en/ do
    devise_for :users
    resources :privacy_policy_acceptances, only: %i[new create index]
    get 'pending_device', to: 'devices#pending', as: :pending_device

    authenticate :user do
      resources :announcements
      resources :invoices, only: %i[index new create update destroy] do
        member do
          get :pdf, defaults: { format: :pdf }
        end
      end
      resources :category_resources, except: %i[show]
      resources :courses, except: %i[destroy] do
        resources :course_lesson_uploads, only: %i[create new show]
      end
      resources :homeworks, only: %i[index new create destroy edit update]
      resources :csv_exports, only: %i[index new show]
      resources :daily_activities, only: %i[create index update]
      resources :english_classes, only: %i[create index update]
      resources :exercises, only: %i[create index update]
      resources :evening_classes, only: %i[create index update]
      resources :files, only: %i[destroy index show]
      resources :homework_resources, only: %i[destroy index]
      resources :kindy_phonics, only: %i[create index update]
      resources :lessons
      resources :lesson_calendars, only: %i[index]
      resources :lesson_searches, only: %i[index]
      resources :lesson_uses, only: %i[index]
      resources :lesson_versions, only: %i[show update]
      resources :level_changes, only: %i[new create]
      resources :missing_lessons, only: %i[index]
      resources :monthly_materials, only: %i[index]
      resources :notifications, except: %i[edit]
      resources :privacy_policies, only: %i[new create show]
      resources :parents_reports, only: %i[create index update]
      resources :proposals, only: %i[show update]
      resources :phonics_classes, only: %i[create index update]
      resources :phonics_resources, only: %i[destroy]
      resources :plans
      resources :school_classes
      resources :seasonal_activities, only: %i[create index update]
      resources :party_activities, only: %i[create index update]
      resources :event_activities, only: %i[create index update]
      resources :report_card_batches, only: %i[index create] do
        post :regenerate, on: :member
      end
      resources :special_lessons, only: %i[create index update]
      resources :stand_show_speaks, only: %i[create index update]
      resources :tutorials
      resources :tutorial_categories
      resources :user_searches, only: %i[index]
      resources :students, except: %i[destroy] do
        member do
          get :icon_chooser
          get :homework_resources
          get :print_version
          get :report_card_pdf
          get :pearson_report, defaults: { format: :pdf }
        end
      end

      resources :student_searches, only: %i[index update]
      resources :support_requests do
        resources :support_messages, only: %i[create]
      end
      resources :teacher_lessons, only: %i[index show]
      resources :teacher_events, only: %i[index show]
      resources :teacher_resources, only: %i[index]
      resources :tests, except: %i[show] do
        resources :test_results, only: %i[create index update]
      end

      resources :organisations, except: %i[destroy] do
        resources :form_submissions, shallow: true
        resources :form_templates, shallow: true
        resources :schools

        resources :student_uploads, only: %i[create new show]
        patch 'student_uploads', to: 'student_uploads#update', as: :student_uploads_update
        resources :teacher_uploads, only: %i[create new show]
        patch 'teacher_uploads', to: 'teacher_uploads#update', as: :teacher_uploads_update
        resources :parent_uploads, only: %i[create new show]
        patch 'parent_uploads', to: 'parent_uploads#update', as: :parent_uploads_update
        resources :pearson_uploads, only: %i[create new show]
        resources :users, except: %i[destroy]
        resources :admins
        resources :org_admins
        resources :parents
        resources :sales
        resources :school_managers
        resources :teachers
        resources :writers
      end
      post 'reassign_editor', to: 'admins#reassign_editor', as: :reassign_editor
      get 'admin_password_change', to: 'admins#new_password_change', as: :admin_password_change
      post 'admin_password_change', to: 'admins#change_password', as: :admin_change_password
      get 'teacher_homework', to: 'homeworks#teacher_index', as: :teacher_homework

      # Index for KU staff who can see everything
      get 'users', to: 'users#index', as: :users
    end

    authenticate :user, ->(user) { user.is?('Admin') } do
      mount Flipper::UI.app(Flipper) => '/flipper', as: :flipper
      mount MissionControl::Jobs::Engine, at: '/jobs'
      mount PgHero::Engine, at: '/pghero'
      resources :devices, only: [:index, :update, :destroy]
      resources :triggerable_jobs, only: %i[index create]
    end

    authenticated :user do
      root to: 'users#show', as: :authenticated_root
    end

    root to: 'splashes#welcome'
  end

  # Receives inquiries from contact form & forwards to Nakagawa
  post 'inquiries' => 'inquiries#create'

  # Health check endpoint
  get 'up' => 'rails/health#show', as: :rails_health_check
end

app/models/users/teacher.rb
# frozen_string_literal: true

class Teacher < User
  include IpLockable, LessonConsumable

  CSV_HEADERS = %w[name email password].freeze
  VISIBLE_TYPES = %w[].freeze

  has_many :class_teachers, dependent: :destroy
  accepts_nested_attributes_for :class_teachers
  has_many :classes, through: :class_teachers,
                     source: :school_class
  has_many :students, through: :classes
  has_many :test_results, through: :students
  has_many :school_teachers, dependent: :destroy
  accepts_nested_attributes_for :school_teachers
  has_many :schools, through: :school_teachers
end

app/controllers/users/teachers_controller.rb
# frozen_string_literal: true

class TeachersController < UsersController
  before_action :set_form_data, only: %i[new edit]

  def show
    @levels = %w[kindy elementary keep_up specialist]
              .select { |level| Flipper.enabled?(:"#{level}", @user) }
  end

  def new
    @user = authorize Teacher.new(organisation_id: params[:organisation_id])
    @orgs = policy_scope(Organisation)

  end

  def edit
    @orgs = policy_scope(Organisation)
  end

  def create
    @orgs = policy_scope(Organisation)
    organisation_id = teachers_params[:organisation_id].presence || current_user.organisation_id
    @user = authorize Teacher.new(teachers_params.merge(organisation_id:))


    if @user.save
      redirect_to organisation_teacher_path(@user.organisation, @user),
                  notice: t('create_success')
    else
      set_form_data
      render :new,
             status: :unprocessable_entity,
             alert: t('create_failure')
    end
  end

  def update
    if @user.update(teachers_params)
      redirect_to organisation_teacher_path(@user.organisation, @user),
                  notice: t('update_success')
    else
      set_form_data
      render :edit,
             status: :unprocessable_entity,
             alert: t('update_failure')
    end
  end

  private

  def set_form_data
    @schools = policy_scope(School).pluck(:name, :id)
    @classes = policy_scope(SchoolClass).pluck(:name, :id)
  end

  def teachers_params
    t_params = [
      :school_id,
      :organisation_id,
      { school_teachers_attributes: %i[id school_id _destroy] },
      { class_teachers_attributes: %i[id class_id _destroy] }
    ]
    params.require(:teacher).permit(user_params + t_params)
  end


  def scoped_users
    super.where(type: 'Teacher')
  end
end

app/helpers/teacher_helper.rb
# frozen_string_literal: true

module TeacherHelper
  def day_link_classes(active, day)
    past = day < Time.zone.today
    'flex flex-col items-center rounded-3xl p-2 ' \
      "#{active ? 'bg-main' : 'bg-secondary'} #{'opacity-50' if past}"
  end

  def day_link_date_classes(active)
    'flex items-center justify-center rounded-full aspect-square bg-white ' \
      "font-bold text-xl p-2 #{active ? 'text-main' : 'text-secondary'}"
  end
end

app/views/teachers/_form.html.haml
-# locals: (classes:, schools:, user:, orgs:)

= form_with model: [user.organisation, user],
            html: { class: 'form',
                    id: 'teacher_form' } do |f|
  = render 'shared/form_errors', resource: user

  = render 'users/fields', f:, orgs:

  - unless current_user.is?('Teacher')
    %h3.text-center.font-bold= t('.schools')
    .flex.flex-wrap.gap-3{ 'data-controller': 'fields' }
      - if user.schools.empty?
        = f.fields_for :school_teachers,
                       user.school_teachers.new(school_id: params[:school_id]) do |st_f|
          = render 'school_teachers/fields', f: st_f, collection: schools,
                                             resource: user
      - else
        = f.fields_for :school_teachers do |st_f|
          = render 'school_teachers/fields', f: st_f, collection: schools,
                                             resource: user

      %template{ 'data-fields-target' => 'template' }
        = f.fields_for :school_teachers,
                       user.school_teachers.new,
                       child_index: 'CHILD' do |st_f|
          = render 'school_teachers/fields', f: st_f, collection: schools,
                                             resource: user

      %div{ 'data-fields-target' => 'target' }

      %button.btn.btn-secondary.w-full{ 'data-action' => 'fields#add' }
        = t('.add_school')

    -# %h3.text-center.font-bold= t('.classes')
    -# .flex.flex-wrap.gap-3{ 'data-controller': 'fields' }
    -#   = f.fields_for :class_teachers do |ct_f|
    -#     = render 'class_teachers/fields', f: ct_f, collection: classes,
    -#                                       resource: user

    -#   %template{ 'data-fields-target' => 'template' }
    -#     = f.fields_for :class_teachers,
    -#                    user.class_teachers.new,
    -#                    child_index: 'CHILD' do |ct_f|
    -#       = render 'class_teachers/fields', f: ct_f, collection: classes,
    -#                                         resource: user

    -#   %div{ 'data-fields-target' => 'target' }

      -# %button.btn.btn-secondary.w-full{ 'data-action' => 'fields#add' }
      -#   = t('.add_class')

  .flex.gap-3
    = f.submit class: 'btn btn-main',
               id: 'submit_teacher'
    - if policy(user).destroy? && !user.new_record?
      = link_to 'Delete',
                organisation_teacher_path(user.organisation, user),
                data: { turbo_method: :delete,
                        turbo_confirm: 'Are you sure you want to delete this teacher?' },
                class: 'btn btn-danger'

app/views/teachers/_nav.html.haml
= main_nav_link 'calendar', lesson_calendars_path
= main_nav_link 'monthly_materials', monthly_materials_path
= main_nav_link 'students', students_path
= main_nav_link 'support', support_requests_path
= main_nav_link 'homework', homeworks_path
= main_nav_link 'test', tests_path
= main_nav_link 'tutorials', tutorials_path
= main_nav_link 'events', teacher_events_path

app/views/teachers/_subtitle.html.haml
-# locals: (date:, level:, teacher:)

:ruby
  in_future = Time.zone.today < date
  in_past = date < Time.zone.today
  formatted_date = if I18n.locale == :ja
  "#{ja_date(date)}"
  else
    date.strftime('%A, %B %d, %Y')
  end
  subtitle = if in_future
    t('.future_lessons', date: formatted_date)
  elsif in_past
    t('.past_lessons', date: formatted_date)
  else
    t('.today_lessons')
  end

%header#subtitle
  = link_to teacher_lessons_path(date: date.prev_weekday,
                                 level:, teacher_id: teacher.id),
            data: { turbo_stream: true },
            class: 'w-12' do
    = image_tag 'back.svg'

  .flex.flex-col.text-center
    %h1= subtitle
    - if !in_past && !in_future
      %small.text-xs.font-normal.text-secondary= formatted_date


  = link_to teacher_lessons_path(date: date.next_weekday,
                                 level:, teacher_id: teacher.id),
            data: { turbo_stream: true },
            class: 'w-12' do
    = image_tag 'next.svg'

  = render 'notifications/icon'
  = render 'notifications/popover_list',
           notifications: current_user.notifications

  .absolute.right-3.top-auto
    = locale_toggle(classes: 'fill-secondary', turbo_stream: true)

app/views/teachers/edit.html.haml
= render 'teachers/form',
         classes: @classes,
         schools: @schools,
         user: @user,
         orgs: @orgs

app/views/teachers/new.html.haml
= render 'teachers/form',
         classes: @classes,
         schools: @schools,
         user: @user,
         orgs: @orgs

app/views/teachers/show.html.haml
:ruby
  base = 'flex gap-6 p-6'
  mobile = 'flex-col justify-start items-stretch'
  desktop = 'md:flex-row md:items-center md:justify-center'
  card = 'card basis-1/3 max-w-full p-3 flex flex-col gap-3'

= render 'teachers/subtitle',
         date: Time.zone.today, level: @levels.first, teacher: @user

%dialog.resources-dialog#lesson-resources
  .body
    %form.h-0
      %button{ formmethod: :dialog }
        = image_tag 'exit.svg', class: 'btn-close'

    = turbo_frame_tag 'lesson'

%main#teacher-lessons{ class: "#{base} #{mobile} #{desktop}" }
  - @levels.each do |level|
    = link_to teacher_lessons_path(level:, teacher_id: @user.id),
              class: card, id: level, data: { turbo_stream: true } do
      = image_tag "levels/#{level}.svg"
      %h1.text-center.text-3xl= t("levels.#{level}")