config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  scope '(/:locale)', locale: /ja|en/ do
    devise_for :users
    resources :privacy_policy_acceptances, only: %i[new create index]
    get 'pending_device', to: 'devices#pending', as: :pending_device

    authenticate :user do
      resources :announcements
      resources :invoices, only: %i[index new create update destroy] do
        member do
          get :pdf, defaults: { format: :pdf }
        end
      end
      resources :category_resources, except: %i[show]
      resources :courses, except: %i[destroy] do
        resources :course_lesson_uploads, only: %i[create new show]
      end
      resources :homeworks, only: %i[index new create destroy edit update]
      resources :csv_exports, only: %i[index new show]
      resources :daily_activities, only: %i[create index update]
      resources :english_classes, only: %i[create index update]
      resources :exercises, only: %i[create index update]
      resources :evening_classes, only: %i[create index update]
      resources :files, only: %i[destroy index show]
      resources :homework_resources, only: %i[destroy index]
      resources :kindy_phonics, only: %i[create index update]
      resources :lessons
      resources :lesson_calendars, only: %i[index]
      resources :lesson_searches, only: %i[index]
      resources :lesson_uses, only: %i[index]
      resources :lesson_versions, only: %i[show update]
      resources :level_changes, only: %i[new create]
      resources :missing_lessons, only: %i[index]
      resources :monthly_materials, only: %i[index]
      resources :notifications, except: %i[edit]
      resources :privacy_policies, only: %i[new create show]
      resources :parents_reports, only: %i[create index update]
      resources :proposals, only: %i[show update]
      resources :phonics_classes, only: %i[create index update]
      resources :phonics_resources, only: %i[destroy]
      resources :plans
      resources :school_classes
      resources :seasonal_activities, only: %i[create index update]
      resources :party_activities, only: %i[create index update]
      resources :event_activities, only: %i[create index update]
      resources :report_card_batches, only: %i[index create] do
        post :regenerate, on: :member
      end
      resources :special_lessons, only: %i[create index update]
      resources :stand_show_speaks, only: %i[create index update]
      resources :tutorials
      resources :tutorial_categories
      resources :user_searches, only: %i[index]
      resources :students, except: %i[destroy] do
        member do
          get :icon_chooser
          get :homework_resources
          get :print_version
          get :report_card_pdf
          get :pearson_report, defaults: { format: :pdf }
        end
      end

      resources :student_searches, only: %i[index update]
      resources :support_requests do
        resources :support_messages, only: %i[create]
      end
      resources :teacher_lessons, only: %i[index show]
      resources :teacher_events, only: %i[index show]
      resources :teacher_resources, only: %i[index]
      resources :tests, except: %i[show] do
        resources :test_results, only: %i[create index update]
      end

      resources :organisations, except: %i[destroy] do
        resources :form_submissions, shallow: true
        resources :form_templates, shallow: true
        resources :schools

        resources :student_uploads, only: %i[create new show]
        patch 'student_uploads', to: 'student_uploads#update', as: :student_uploads_update
        resources :teacher_uploads, only: %i[create new show]
        patch 'teacher_uploads', to: 'teacher_uploads#update', as: :teacher_uploads_update
        resources :parent_uploads, only: %i[create new show]
        patch 'parent_uploads', to: 'parent_uploads#update', as: :parent_uploads_update
        resources :pearson_uploads, only: %i[create new show]
        resources :users, except: %i[destroy]
        resources :admins
        resources :org_admins
        resources :parents
        resources :sales
        resources :school_managers
        resources :teachers
        resources :writers
      end
      post 'reassign_editor', to: 'admins#reassign_editor', as: :reassign_editor
      get 'admin_password_change', to: 'admins#new_password_change', as: :admin_password_change
      post 'admin_password_change', to: 'admins#change_password', as: :admin_change_password
      get 'teacher_homework', to: 'homeworks#teacher_index', as: :teacher_homework

      # Index for KU staff who can see everything
      get 'users', to: 'users#index', as: :users
    end

    authenticate :user, ->(user) { user.is?('Admin') } do
      mount Flipper::UI.app(Flipper) => '/flipper', as: :flipper
      mount MissionControl::Jobs::Engine, at: '/jobs'
      mount PgHero::Engine, at: '/pghero'
      resources :devices, only: [:index, :update, :destroy]
      resources :triggerable_jobs, only: %i[index create]
    end

    authenticated :user do
      root to: 'users#show', as: :authenticated_root
    end

    root to: 'splashes#welcome'
  end

  # Receives inquiries from contact form & forwards to Nakagawa
  post 'inquiries' => 'inquiries#create'

  # Health check endpoint
  get 'up' => 'rails/health#show', as: :rails_health_check
end

app/controllers/lessons/teacher_lessons_controller.rb
# frozen_string_literal: true

class TeacherLessonsController < ApplicationController
  after_action :verify_authorized, only: %i[show]

  def index
    respond_to do |format|
      format.turbo_stream { index_vars }
    end
  end

  def show
    set_date_level_teacher
    @type = validated_type(params[:type])
    @type_lessons, @lesson = lessons_for_type(@teacher, @date, @level, @type)
    @resources = set_resources
    @lesson_links = set_links
  end

  private

  def index_vars
    set_date_level_teacher
    @types = @teacher.day_lessons(@date)
                     .send(@level).pluck(:type).uniq
    @announcements = Pundit.policy_scope!(@teacher, Announcement)
  end

  def set_date_level_teacher
    @teacher = Teacher.find(params[:teacher_id])
    @date = params[:date] ? Date.parse(params[:date]) : Time.zone.today
    @level = validated_level(params[:level], @teacher)
  end

  def set_resources
    resources = @lesson.resources.includes(:blob)
    resources += phonics_resources if @type == 'PhonicsClass'

    resources.sort_by { |r| r.blob.filename }
  end

  def set_links
    @lesson.lesson_links
  end

  def phonics_resources
    course_lesson = @teacher.course_lessons.find_by(lesson_id: @lesson.id)
    return PhonicsResource.none unless course_lesson

    plan = @teacher.plans.find_by(course_id: course_lesson.course_id)
    return PhonicsResource.none unless plan

    week = @teacher.course_week(plan, @date)

    @lesson.phonics_resources
           .for_course_week(course_lesson.course_id, week)
           .includes(:blob)
  end

  def validated_level(level_param, teacher)
    @valid_levels = %w[kindy elementary keep_up specialist]
                    .select { |level| Flipper.enabled?(:"#{level}", teacher) }
    if @valid_levels.none?(level_param)
      return redirect_back fallback_location: root_path,
                           alert: "Invalid level: #{level_param}"
    end

    level_param
  end

  def validated_type(type_param)
    if Lesson::TYPES.none?(type_param)
      return redirect_back fallback_location: root_path,
                           alert: "Invalid level: #{type_param}"
    end

    type_param
  end

  def lessons_for_type(teacher, date, level, type)
    type_lessons = teacher.day_lessons(date)
                          .send(level).where(type:)
                          .order(level: :asc)
    lesson = if params[:id].to_i.zero?
               authorize type_lessons.first
             else
               authorize type_lessons.find(params[:id])
             end

    [type_lessons, lesson]
  end
end

app/helpers/teacher_lesson_helper.rb
# frozen_string_literal: true

module TeacherLessonHelper
  def lesson_type_heading(lesson)
    heading = case lesson.type
              when 'KindyPhonic', 'PhonicsClass'
                'phonics'
              when 'SpecialLesson', 'SeasonalActivity', 'EventActivity', 'PartyActivity'
                lesson.title
              else
                lesson.type.underscore
              end

    t("lessons.#{heading}")
  end

  def lesson_type_order(level)
    order = {
      'kindy' => %w[arrival sensory_play get_up_and_go snack SpecialLesson DailyActivity
                    Exercise KindyPhonic story_and_reading friendship_time EnglishClass StandShowSpeak bus_time],
      'elementary' => %w[arrival brush_up snack SpecialLesson DailyActivity
                         Exercise daily_gathering PhonicsClass EnglishClass
                         StandShowSpeak bus_time],
      'keep_up' => %w[conversation_time snack book_activity EveningClass
                      lesson_review],
      'specialist' => %w[homework_check break_&_quiz four_skills project
                         EveningClass]
    }[level]
    return order if Flipper.enabled?(:afterschool_extras, current_user)

    order - CategoryResource::AFTERSCHOOL_EXTRAS
  end

  def lesson_image_tag(lesson, type, **)
    src = lesson.cover_image.attached? ? url_for(lesson.cover_image) : asset_path("levels/#{type.downcase}.svg")
    image_tag(src, **)
  end

  def tutorial_image_tag(category, **)
    src = category.cover_image.attached? ? url_for(category.cover_image) : asset_path('tutorials.svg')
    image_tag(src, **)
  end

  def lesson_level_heading(lesson)
    if %w[DailyActivity Exercise].include?(lesson.type)
      t("lessons.subtypes.#{lesson.subtype}")
    else
      t("levels.#{lesson.short_level.downcase.tr(' ', '_')}").upcase
    end
  end

  def lesson_details_heading(lesson)
    case lesson.type
    when 'DailyActivity', 'Exercise'
      lesson.title
    when 'EnglishClass', 'KindyPhonic'
      lesson.topic
    else
      lesson.goal
    end
  end

  def lvl_border_class(level)
    lvl_classes = { 'Kindy' => 'border-kindy', 'Land' => 'border-land',
                    'Sky' => 'border-sky', 'Galaxy' => 'border-galaxy',
                    'Keep Up' => 'border-keep-up',
                    'Specialist' => 'border-specialist' }

    lvl_classes[level] || 'border-secondary'
  end

  def lvl_text_class(level)
    lvl_classes = { 'Kindy' => 'text-kindy', 'Land' => 'text-land',
                    'Sky' => 'text-sky', 'Galaxy' => 'text-galaxy',
                    'Keep Up' => 'text-keep-up',
                    'Specialist' => 'text-specialist' }

    lvl_classes[level] || 'text-secondary'
  end
end

app/views/teacher_lessons/_card.html.haml
-# locals: (date:, level:, teacher_id:, type:)

- if Lesson::TYPES.include?(type)
  :ruby
    src = teacher_lesson_path(0, date:, level:, type:, teacher_id:)
    title = if type == 'EveningClass'
      level == 'specialist' ? 'research_study' : 'topic_study'
    elsif type.include?('Phonic')
      'phonics'
    else
      type.underscore
    end

  %button{ class: 'card flex flex-col items-center p-2 gap-2',
           data: { action: 'dialog#open',
                   controller: 'dialog',
                   'dialog-dialog-value': 'lesson-resources',
                   'dialog-frame-value': 'lesson',
                   'dialog-src-value': src },
           type: 'button' }
    = image_tag "lesson_types/#{type.underscore}.svg",
                class: 'h-full'
    %hr{ class: 'w-4/5 border border-secondary rounded -mb-1' }
    %h3.text-center= t("lessons.#{title}")

- else
  :ruby
    evening_types = %w[homework_check break_&_quiz four_skills project
                       conversation_time book_activity lesson_review]

    category = if evening_types.include?(type)
      'evening_class'
    else
      type.underscore
    end

    # only show the card if there are resources for this category
    scope = policy_scope(CategoryResource)
    has_resources = scope.public_send(category).exists?

  - if has_resources
    = link_to teacher_resources_path(category:),
              class: 'card flex flex-col items-center p-2 gap-2',
              data: { turbo_frame: '_top' } do
      = image_tag "lesson_types/#{category}.svg",
                  class: 'h-full'
      %hr{ class: 'w-4/5 border border-secondary rounded -mb-1' }
      %h3.text-center= t("category_resources.#{type}")

app/views/teacher_lessons/_evening_cards.html.haml
-# locals: (level:)

:ruby
  types = if level == 'specialist'
    %w[homework_check break_&_quiz four_skills project]
  elsif level == 'keep_up'
    %w[conversation_time snack book_activity]
  end

-# this will be a file_path link, or to public
- types.each do |type|
  = link_to '',
            class: 'card flex flex-col items-center p-2 gap-2' do
    = image_tag "lesson_types/#{type.underscore}.svg",
                class: 'h-full'
    %hr{ class: 'w-4/5 border border-secondary rounded -mb-1' }
    %h3.text-center= type.titleize

app/views/teacher_lessons/_guide_section.html.haml
-# locals: (lesson:)

%section{ class: 'w-full md:w-1/3' }
  = link_to file_path(id: lesson.guide.blob.id),
            target: '_blank',
            rel: 'noopener',
            class: 'btn-outline' do
    %span{ class: 'basis-5/6 truncate' }= t('.guide')
    = inline_svg_tag 'download_icon.svg',
                     class: 'fill-secondary'

app/views/teacher_lessons/_links_section.html.haml
-# locals: (lesson_links:)
%h3.font-bold.text-left Links

%section.resource-section

  .flex.flex-wrap.justify-start.items-center.gap-3.mt-2
    - lesson_links.each do |link|
      - title = link.title.presence || (URI.parse(link.url).host rescue 'Link')
      - preview_url = link.video? ? (link.embed_url.presence || link.url) : link.url

      - if link.video?
        %a.btn-outline.w-full.flex.items-center{
          href: "#",
          data: {
            controller: "dialog",
            action: "click->dialog#open",
            "dialog-dialog-value" => "lesson-video",
            "dialog-frame-value"  => "lesson-video-frame",
            "dialog-src-value"    => preview_url
          }
        }
          %span{ class: "basis-5/6 truncate" }= title
          = inline_svg_tag 'download_icon.svg', class: 'fill-secondary basis-1/6'

      - else
        = link_to preview_url, target: "_blank", rel: "noopener",
                  class: "btn-outline w-full flex items-center" do
          %span{ class: "basis-5/6 truncate" }= title
          = inline_svg_tag 'download_icon.svg', class: 'fill-secondary basis-1/6'

app/views/teacher_lessons/_tabs.html.haml
-# locals: (active_lesson:, date:, lessons:, level:, teacher_id:, type:)

:ruby
  return if lessons.size <= 1

  subtype_lessons = %w[DailyActivity Exercise]

- lessons.each do |l|
  - active = l == active_lesson

  = link_to teacher_lesson_path(l, teacher_id:, type:, level:, date:),
            class: "tab #{active ? 'active' : 'inactive'}" do
    - if subtype_lessons.include?(l.type)
      = image_tag type_icon_path(l)
    - else
      = image_tag level_icon_path(l)

app/views/teacher_lessons/index.turbo_stream.haml
= turbo_stream.replace 'subtitle' do
  = render partial: 'teachers/subtitle',
           locals: { date: @date, level: @level, teacher: @teacher }

= turbo_stream.replace 'teacher-lessons' do
  %main.p-6.flex.flex-col.gap-3#teacher-lessons
    - if @announcements.any?
      = render 'shared/announcement_list', announcements: @announcements

    %nav.tab-nav
      - @valid_levels.each do |level|
        = link_to t("levels.#{level}"),
                  teacher_lessons_path(date: @date, level:,
                                       teacher_id: @teacher.id),
                  class: "nav-tab #{@level == level ? 'active' : 'inactive'}",
                  data: { turbo_stream: true }

    %section.grid.grid-cols-2.md:grid-cols-5.gap-3.py-6
      - lesson_type_order(@level).each do |type|
        - next if Lesson::TYPES.include?(type) && @types.exclude?(type)

        = render partial: 'teacher_lessons/card',
                 locals: { date: @date, level: @level,
                           teacher_id: @teacher.id, type: }

app/views/teacher_lessons/phonics_class.html.haml
:ruby
  border = "border-b-2 #{lvl_border(@lesson.short_level)}"
  text = lvl_text(@lesson.short_level)

= turbo_frame_tag 'lesson' do
  = render 'teacher_lessons/tabs',
           lessons: @type_lessons, active_lesson: @lesson, level: @level,
           teacher_id: @teacher.id, type: @type, date: @date

  .content
    %header
      %h1{ class: "type #{border}" }
        = @lesson.type.titleize
      %h1{ class: "level #{text} #{border}" }
        = @lesson.short_level.upcase
      = image_tag type_icon_path(@lesson)
      %h3.details= @lesson.goal

    - if @lesson.guide.attached?
      = render 'teacher_lessons/guide_section',
               lesson: @lesson

    - if @resources.any?
      = render 'teacher_lessons/resources_section',
               resources: @resources

app/views/teacher_lessons/show.html.haml
:ruby
  border = "border-b-2 #{lvl_border_class(@lesson.short_level)}"
  text = lvl_text_class(@lesson.short_level)

= turbo_frame_tag 'lesson' do
  = render 'teacher_lessons/tabs',
           lessons: @type_lessons, active_lesson: @lesson, level: @level,
           teacher_id: @teacher.id, type: @type, date: @date

  %dialog.resources-dialog#lesson-video.video-dialog
    .body.p-4.flex.justify-center.items-center
      %form.h-0
        %button{ formmethod: :dialog }
          = image_tag 'exit.svg', class: 'btn-close'

      %iframe#lesson-video-frame{
        src: "",
        frameborder: 0,
        allow: "accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture",
        allowfullscreen: true,
        class: "w-full h-full"
      }

  .dialog-content
    %header
      %h1{ class: "type #{border}" }
        = lesson_type_heading(@lesson)
      %h1{ class: "level #{text} #{border}" }
        = lesson_level_heading(@lesson)
      = image_tag type_icon_path(@lesson), class: 'h-full place-self-end'
      %h3.details= lesson_details_heading(@lesson)

    - if @lesson.guide.attached?
      = render 'teacher_lessons/guide_section',
               lesson: @lesson

    - if @resources.any?
      = render 'teacher_lessons/resources_section',
               resources: @resources

    - if @lesson_links.any?
      = render 'teacher_lessons/links_section',
               lesson_links: @lesson_links